import { apiFetch } from "../client";
import {
  type PlayerStatisticDto,
  type TeamSeasonStatisticDto,
  playerStatisticSchema,
  teamSeasonStatisticSchema,
} from "../schemas/statistics.schema";
import { z } from "zod";

// Fallback mock data cho Football Cầu thủ
const mockFootballPlayers: PlayerStatisticDto[] = [
  {
    id: "fp-1",
    playerId: "p-1",
    playerName: "Erling Haaland",
    teamId: "t-1",
    teamName: "Manchester City",
    teamLogoUrl: "https://media.api-sports.io/football/teams/50.png",
    season: "2025-2026",
    sport: "football",
    position: "Attacker",
    nationality: "Norway",
    appearances: 26,
    minutesPlayed: 2280,
    goals: 24,
    assists: 5,
    yellowCards: 2,
    redCards: 0,
    shotsOnTarget: 58,
  },
  {
    id: "fp-2",
    playerId: "p-2",
    playerName: "Mohamed Salah",
    teamId: "t-2",
    teamName: "Liverpool",
    teamLogoUrl: "https://media.api-sports.io/football/teams/40.png",
    season: "2025-2026",
    sport: "football",
    position: "Attacker",
    nationality: "Egypt",
    appearances: 27,
    minutesPlayed: 2340,
    goals: 21,
    assists: 14,
    yellowCards: 1,
    redCards: 0,
    shotsOnTarget: 52,
  },
  {
    id: "fp-3",
    playerId: "p-3",
    playerName: "Bukayo Saka",
    teamId: "t-3",
    teamName: "Arsenal",
    teamLogoUrl: "https://media.api-sports.io/football/teams/42.png",
    season: "2025-2026",
    sport: "football",
    position: "Midfielder",
    nationality: "England",
    appearances: 25,
    minutesPlayed: 2150,
    goals: 15,
    assists: 12,
    yellowCards: 3,
    redCards: 0,
    shotsOnTarget: 41,
  },
  {
    id: "fp-4",
    playerId: "p-4",
    playerName: "Cole Palmer",
    teamId: "t-4",
    teamName: "Chelsea",
    teamLogoUrl: "https://media.api-sports.io/football/teams/49.png",
    season: "2025-2026",
    sport: "football",
    position: "Midfielder",
    nationality: "England",
    appearances: 26,
    minutesPlayed: 2200,
    goals: 16,
    assists: 10,
    yellowCards: 4,
    redCards: 0,
    shotsOnTarget: 45,
  },
  {
    id: "fp-5",
    playerId: "p-5",
    playerName: "Alexander Isak",
    teamId: "t-5",
    teamName: "Newcastle United",
    teamLogoUrl: "https://media.api-sports.io/football/teams/34.png",
    season: "2025-2026",
    sport: "football",
    position: "Attacker",
    nationality: "Sweden",
    appearances: 23,
    minutesPlayed: 1980,
    goals: 17,
    assists: 3,
    yellowCards: 2,
    redCards: 0,
    shotsOnTarget: 38,
  },
  {
    id: "fp-6",
    playerId: "p-6",
    playerName: "Son Heung-Min",
    teamId: "t-6",
    teamName: "Tottenham",
    teamLogoUrl: "https://media.api-sports.io/football/teams/47.png",
    season: "2025-2026",
    sport: "football",
    position: "Attacker",
    nationality: "South Korea",
    appearances: 25,
    minutesPlayed: 2110,
    goals: 12,
    assists: 9,
    yellowCards: 1,
    redCards: 0,
    shotsOnTarget: 34,
  },
  {
    id: "fp-7",
    playerId: "p-7",
    playerName: "Kevin De Bruyne",
    teamId: "t-1",
    teamName: "Manchester City",
    teamLogoUrl: "https://media.api-sports.io/football/teams/50.png",
    season: "2025-2026",
    sport: "football",
    position: "Midfielder",
    nationality: "Belgium",
    appearances: 20,
    minutesPlayed: 1600,
    goals: 6,
    assists: 15,
    yellowCards: 2,
    redCards: 0,
    shotsOnTarget: 22,
  },
  {
    id: "fp-8",
    playerId: "p-8",
    playerName: "Bruno Fernandes",
    teamId: "t-7",
    teamName: "Manchester United",
    teamLogoUrl: "https://media.api-sports.io/football/teams/33.png",
    season: "2025-2026",
    sport: "football",
    position: "Midfielder",
    nationality: "Portugal",
    appearances: 27,
    minutesPlayed: 2410,
    goals: 9,
    assists: 11,
    yellowCards: 5,
    redCards: 1,
    shotsOnTarget: 36,
  }
];

// Fallback mock data cho Basketball Cầu thủ
const mockBasketballPlayers: PlayerStatisticDto[] = [
  {
    id: "bp-1",
    playerId: "b-1",
    playerName: "Luka Dončić",
    teamId: "tb-1",
    teamName: "Dallas Mavericks",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/138.png",
    season: "2025-2026",
    sport: "basketball",
    position: "Guard",
    appearances: 55,
    minutesPlayed: 2050,
    pointsAvg: 33.8,
    reboundsAvg: 9.2,
    assistsAvg: 9.8,
    stealsAvg: 1.5,
    blocksAvg: 0.6,
    fieldGoalPercentage: 48.7,
  },
  {
    id: "bp-2",
    playerId: "b-2",
    playerName: "Giannis Antetokounmpo",
    teamId: "tb-2",
    teamName: "Milwaukee Bucks",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/146.png",
    season: "2025-2026",
    sport: "basketball",
    position: "Forward",
    appearances: 58,
    minutesPlayed: 2030,
    pointsAvg: 30.6,
    reboundsAvg: 11.4,
    assistsAvg: 6.4,
    stealsAvg: 1.2,
    blocksAvg: 1.1,
    fieldGoalPercentage: 60.5,
  },
  {
    id: "bp-3",
    playerId: "b-3",
    playerName: "Shai Gilgeous-Alexander",
    teamId: "tb-3",
    teamName: "Oklahoma City Thunder",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/150.png",
    season: "2025-2026",
    sport: "basketball",
    position: "Guard",
    appearances: 60,
    minutesPlayed: 2070,
    pointsAvg: 31.1,
    reboundsAvg: 5.6,
    assistsAvg: 6.3,
    stealsAvg: 2.1,
    blocksAvg: 0.9,
    fieldGoalPercentage: 53.8,
  },
  {
    id: "bp-4",
    playerId: "b-4",
    playerName: "Nikola Jokić",
    teamId: "tb-4",
    teamName: "Denver Nuggets",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/139.png",
    season: "2025-2026",
    sport: "basketball",
    position: "Center",
    appearances: 62,
    minutesPlayed: 2150,
    pointsAvg: 26.4,
    reboundsAvg: 12.3,
    assistsAvg: 9.0,
    stealsAvg: 1.4,
    blocksAvg: 0.9,
    fieldGoalPercentage: 58.2,
  },
  {
    id: "bp-5",
    playerId: "b-5",
    playerName: "Jayson Tatum",
    teamId: "tb-5",
    teamName: "Boston Celtics",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/133.png",
    season: "2025-2026",
    sport: "basketball",
    position: "Forward",
    appearances: 59,
    minutesPlayed: 2110,
    pointsAvg: 27.2,
    reboundsAvg: 8.3,
    assistsAvg: 4.9,
    stealsAvg: 1.0,
    blocksAvg: 0.6,
    fieldGoalPercentage: 47.3,
  },
  {
    id: "bp-6",
    playerId: "b-6",
    playerName: "Stephen Curry",
    teamId: "tb-6",
    teamName: "Golden State Warriors",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/141.png",
    season: "2025-2026",
    sport: "basketball",
    position: "Guard",
    appearances: 56,
    minutesPlayed: 1840,
    pointsAvg: 26.8,
    reboundsAvg: 4.4,
    assistsAvg: 5.1,
    stealsAvg: 0.8,
    blocksAvg: 0.4,
    fieldGoalPercentage: 45.1,
  },
  {
    id: "bp-7",
    playerId: "b-7",
    playerName: "LeBron James",
    teamId: "tb-7",
    teamName: "Los Angeles Lakers",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/144.png",
    season: "2025-2026",
    sport: "basketball",
    position: "Forward",
    appearances: 54,
    minutesPlayed: 1900,
    pointsAvg: 25.5,
    reboundsAvg: 7.2,
    assistsAvg: 8.2,
    stealsAvg: 1.2,
    blocksAvg: 0.6,
    fieldGoalPercentage: 53.5,
  },
  {
    id: "bp-8",
    playerId: "b-8",
    playerName: "Anthony Edwards",
    teamId: "tb-8",
    teamName: "Minnesota Timberwolves",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/147.png",
    season: "2025-2026",
    sport: "basketball",
    position: "Guard",
    appearances: 61,
    minutesPlayed: 2140,
    pointsAvg: 26.1,
    reboundsAvg: 5.5,
    assistsAvg: 5.2,
    stealsAvg: 1.3,
    blocksAvg: 0.5,
    fieldGoalPercentage: 46.5,
  }
];

// Mock Football Đội bóng
const mockFootballTeams: TeamSeasonStatisticDto[] = [
  {
    id: "ft-1",
    teamId: "t-2",
    teamName: "Liverpool",
    teamLogoUrl: "https://media.api-sports.io/football/teams/40.png",
    season: "2025-2026",
    sport: "football",
    played: 28,
    wins: 20,
    draws: 5,
    losses: 3,
    goalsFor: 68,
    goalsAgainst: 25,
    goalDifference: 43,
    cleanSheets: 12,
  },
  {
    id: "ft-2",
    teamId: "t-3",
    teamName: "Arsenal",
    teamLogoUrl: "https://media.api-sports.io/football/teams/42.png",
    season: "2025-2026",
    sport: "football",
    played: 28,
    wins: 19,
    draws: 6,
    losses: 3,
    goalsFor: 62,
    goalsAgainst: 22,
    goalDifference: 40,
    cleanSheets: 14,
  },
  {
    id: "ft-3",
    teamId: "t-1",
    teamName: "Manchester City",
    teamLogoUrl: "https://media.api-sports.io/football/teams/50.png",
    season: "2025-2026",
    sport: "football",
    played: 28,
    wins: 18,
    draws: 5,
    losses: 5,
    goalsFor: 65,
    goalsAgainst: 30,
    goalDifference: 35,
    cleanSheets: 10,
  },
  {
    id: "ft-4",
    teamId: "t-4",
    teamName: "Chelsea",
    teamLogoUrl: "https://media.api-sports.io/football/teams/49.png",
    season: "2025-2026",
    sport: "football",
    played: 28,
    wins: 15,
    draws: 7,
    losses: 6,
    goalsFor: 54,
    goalsAgainst: 36,
    goalDifference: 18,
    cleanSheets: 8,
  },
  {
    id: "ft-5",
    teamId: "t-5",
    teamName: "Newcastle United",
    teamLogoUrl: "https://media.api-sports.io/football/teams/34.png",
    season: "2025-2026",
    sport: "football",
    played: 28,
    wins: 14,
    draws: 5,
    losses: 9,
    goalsFor: 49,
    goalsAgainst: 37,
    goalDifference: 12,
    cleanSheets: 9,
  }
];

// Mock Basketball Đội bóng
const mockBasketballTeams: TeamSeasonStatisticDto[] = [
  {
    id: "bt-1",
    teamId: "tb-5",
    teamName: "Boston Celtics",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/133.png",
    season: "2025-2026",
    sport: "basketball",
    played: 64,
    wins: 48,
    draws: null,
    losses: 16,
    winPercentage: 0.75,
    pointsForAvg: 120.5,
    pointsAgainstAvg: 109.2,
    pointDifferential: 11.3,
  },
  {
    id: "bt-2",
    teamId: "tb-3",
    teamName: "Oklahoma City Thunder",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/150.png",
    season: "2025-2026",
    sport: "basketball",
    played: 63,
    wins: 47,
    draws: null,
    losses: 16,
    winPercentage: 0.746,
    pointsForAvg: 119.8,
    pointsAgainstAvg: 111.4,
    pointDifferential: 8.4,
  },
  {
    id: "bt-3",
    teamId: "tb-4",
    teamName: "Denver Nuggets",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/139.png",
    season: "2025-2026",
    sport: "basketball",
    played: 65,
    wins: 44,
    draws: null,
    losses: 21,
    winPercentage: 0.677,
    pointsForAvg: 115.6,
    pointsAgainstAvg: 110.1,
    pointDifferential: 5.5,
  },
  {
    id: "bt-4",
    teamId: "tb-2",
    teamName: "Milwaukee Bucks",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/146.png",
    season: "2025-2026",
    sport: "basketball",
    played: 64,
    wins: 42,
    draws: null,
    losses: 22,
    winPercentage: 0.656,
    pointsForAvg: 118.9,
    pointsAgainstAvg: 115.8,
    pointDifferential: 3.1,
  },
  {
    id: "bt-5",
    teamId: "tb-7",
    teamName: "Los Angeles Lakers",
    teamLogoUrl: "https://media.api-sports.io/basketball/teams/144.png",
    season: "2025-2026",
    sport: "basketball",
    played: 64,
    wins: 38,
    draws: null,
    losses: 26,
    winPercentage: 0.594,
    pointsForAvg: 117.2,
    pointsAgainstAvg: 116.5,
    pointDifferential: 0.7,
  }
];

export async function getPlayerStatistics(params: {
  sport: "football" | "basketball";
  leagueId?: string;
  season?: string;
  sortBy?: string;
}): Promise<PlayerStatisticDto[]> {
  try {
    const query = new URLSearchParams({
      sport: params.sport,
      ...(params.leagueId && { leagueId: params.leagueId }),
      ...(params.season && { season: params.season }),
      ...(params.sortBy && { sortBy: params.sortBy }),
    }).toString();

    const response = await apiFetch<unknown>(`/statistics/players?${query}`);
    return z.array(playerStatisticSchema).parse(response.data);
  } catch (error) {
    // Trả về mock data chất lượng cao khi API backend đang hoàn thiện
    const list = params.sport === "basketball" ? mockBasketballPlayers : mockFootballPlayers;
    
    // Sort logic cho mock
    if (params.sortBy) {
      return [...list].sort((a, b) => {
        const valA = (a as Record<string, unknown>)[params.sortBy!] as number ?? 0;
        const valB = (b as Record<string, unknown>)[params.sortBy!] as number ?? 0;
        return valB - valA;
      });
    }
    return list;
  }
}

export async function getTeamSeasonStatistics(params: {
  sport: "football" | "basketball";
  leagueId?: string;
  season?: string;
}): Promise<TeamSeasonStatisticDto[]> {
  try {
    const query = new URLSearchParams({
      sport: params.sport,
      ...(params.leagueId && { leagueId: params.leagueId }),
      ...(params.season && { season: params.season }),
    }).toString();

    const response = await apiFetch<unknown>(`/statistics/teams?${query}`);
    return z.array(teamSeasonStatisticSchema).parse(response.data);
  } catch (error) {
    // Trả về mock data khi API backend chưa có sẵn
    return params.sport === "basketball" ? mockBasketballTeams : mockFootballTeams;
  }
}
